### ISSUE TITLE
lib>helper>utils>file.jsx

### ISSUE THREAD

**Issue by waterlooSunset** [bastienEichenberger/extendscript-library#5]
file.jsx overwrites extendscript native implementation of read() and write() methods and assumes UTF8 encoding on all File objects passed in as parameters. 

Run the following with and with out the .read() library function. The native implementation returns the expected data.

```javascript
var blob;
var bin = File('/c/path/to/some/binaryFile.bin');
bin.encoding = 'BINARY';
bin.open('r');
blob = bin.read();
bin.close();
alert(blob);
```

Suggest renaming .read() and .write() methods in lib.helper.utils.file.jsx to .readUTF8() and .writeUTF8() or something similar.

**Comment by bastienEichenberger** [comment]
Hi,
Thank you for your Message.
This is a good Suggestion.

Do not hesitage to contribute and add more function into the Library.
We will start new Projects in few month with this Library. So the Repository will be more active.

Best regards.

**Comment by jonasoesch** [comment]
Cool, c’est encore vivant :-)

Salutations, Jonas

Am 18. August 2016 um 14:25:13, Eichenberger (notifications@github.com) schrieb:

Hi,
Thank you for your Message.
This is a good Suggestion.

Do not hesitage to contribute and add more function into the Library.
We will start new Projects in few month with this Library. So the Repository will be more active.

Best regards.

**Comment by bastienEichenberger** [comment]
@jonasoesch Oui tout à fait! Nous avons même développés plusieurs scripts qui fonctionnent très bien dans notre entreprise. Si tu veux une démo n'hésite-pas à venir nous voir à Lausanne? www.images3.ch

**Comment by jonasoesch** [comment]
Ce sont de bonnes nouvelles. Je serai sur Lausanne la 30 août. Est-ce que tu travailles cette journée ?

– Jonas

Am 18. August 2016 um 16:14:24, Eichenberger (notifications@github.com) schrieb:

@jonasoesch Oui tout à fait! Nous avons même développés plusieurs scripts qui fonctionnent très bien dans notre entreprise. Si tu veux une démo n'hésite-pas à venir nous voir à Lausanne? www.images3.ch

**Comment by waterlooSunset** [comment]
Resolved with commit #7adf281 by @bastienEichenberger
